-- Lot-wide package size sent with every eBay listing in the lot.
ALTER TABLE "ExportProfile" ADD COLUMN IF NOT EXISTS "packageWeightOz" DOUBLE PRECISION NOT NULL DEFAULT 4;
ALTER TABLE "ExportProfile" ADD COLUMN IF NOT EXISTS "packageLengthIn" DOUBLE PRECISION NOT NULL DEFAULT 7;
ALTER TABLE "ExportProfile" ADD COLUMN IF NOT EXISTS "packageWidthIn" DOUBLE PRECISION NOT NULL DEFAULT 5;
ALTER TABLE "ExportProfile" ADD COLUMN IF NOT EXISTS "packageHeightIn" DOUBLE PRECISION NOT NULL DEFAULT 2;
